sonar.projectKey=hlan-net_jfyi-just-for-your-information
sonar.organization=hlan-net

# Source and test paths
sonar.sources=src
sonar.tests=tests

# Code coverage report
sonar.python.coverage.reportPaths=coverage.xml

# Exclude CI workflows and static assets from code analysis
sonar.exclusions=.github/workflows/**,helm/**,pages/**
