apiVersion: v1
kind: Service
metadata:
  name: {{ include "jfyi-mcp-server.fullname" . }}-service
  labels:
    {{- include "jfyi-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "jfyi-mcp-server.selectorLabels" . | nindent 4 }}
